---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/akaihola/darker
      rev: 1.3.2
      hooks:
          - id: darker
            args: [--isort, -L, mypy, -L pylint, -L, flake8]
            additional_dependencies: [isort]
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.26.3  # or higher tag
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0  # or specific tag
      hooks:
          - id: yamlfmt
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.29.0
      hooks:
          - id: pyupgrade
    - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
      rev: v2.2.0
      hooks:
          - id: pretty-format-toml
            args: [--autofix]
    - repo: https://github.com/koalaman/shellcheck-precommit
      rev: v0.7.2
      hooks:
          - id: shellcheck
    - repo: https://github.com/pycqa/isort
      rev: 5.9.3
      hooks:
          - id: isort
            name: isort (python)
            args: [--profile, black]
          - id: isort
            name: isort (cython)
            types: [cython]
          - id: isort
            name: isort (pyi)
            types: [pyi]
